### ISSUE TITLE
Issues regarding version value for upcoming release

### ISSUE THREAD

**Issue by David-Rod** [qiime2/q2studio#177]
**Bug Description**
The issues may possibly be related to the version values in `package.json` (line 3) and `setup.py` (line 16). There seems to be a history of removing `dev` from these values around the time of each release and may be impacting the expected value for `version`.

See #176 

**Steps to reproduce the behavior**
Issues are present when a commit is made to the repository. `make test` was ran locally and there were no errors present.

**Screenshots**
Please see Travis details for more on this issue.

<img width="917" alt="image" src="https://user-images.githubusercontent.com/30784905/72557078-3cb79680-385d-11ea-8486-bfb094252237.png">

**Computation Environment**
- OS: Mojave
- QIIME 2 Release 2019.10 (dev env)

**Comment by ebolyen** [comment]
Fixed in master, but there's some new issues on Travis. I'll try to sort that out on Monday.
