### ISSUE TITLE
Is there a WebApp?

### ISSUE THREAD

**Issue by caio-davi** [qiime2/q2studio#190]
**Improvement Description**
Create a webApp version.

**Current Behavior**
There is only the electronApp option, it then runs the server-side on the client machine. But we commonly find servers/clusters dedicated to run bioinformatic jobs, including QIIME2 jobs. It might be interesting to have this option, and on a first looking at the electronApp, it seems to be pretty feasible. 

**Proposed Behavior**
Change some confs on the `/src` and create a new script on `package.json` to run the app as a webApp. 
Alternatively, we could run only the q2studio API on the server-side and create a `connect-to-server` section on the electronApp, changing the connection info.
I'm not familiar with electron, so I don't know how hard would be those changes, neither which one would be the best option at the moment.

**Comment by thermokarst** [comment]
Thanks @caio-davi - we are actually in the middle of building [q2galaxy](https://github.com/qiime2/q2galaxy/), which will likely be the premier GUI for QIIME 2 in the near future. This builds on top of the Galaxy ecosystem, so running QIIME 2 as a webapp would be supported there as a first-class citizen.

**Comment by caio-davi** [comment]
Thank you for let me know. It sounds awesome!
I'll take a look at the repository, and I would love to collaborate with it.

I'll go ahead and close this issue since it seems to be fully contemplated by this other project.

**Comment by thermokarst** [comment]
Thanks @caio-davi  - we would love to collaborate!
