### ISSUE TITLE
ENH: Specify source format during importing

### ISSUE THREAD

**Issue by thermokarst** [qiime2/q2studio#75]
`q2cli` users have the ability to specify the `source_format` when importing data, it would be great to have feature parity in `q2studio`.

See https://github.com/qiime2/q2cli/pull/57 for more details on the `q2cli` implementation.

**Comment by ebolyen** [comment]
It would be great if there was a way to list transformations available for a directory format (and by proxy what formats could be used)

**Comment by maxvonhippel** [comment]
[Working on this](https://github.com/maxvonhippel/q2studio).

**Comment by jairideout** [comment]
Fixed in #111

**Comment by maxvonhippel** [comment]
If I put a `BIOMV100Format` file in a folder, select that directory when I click `import` to add an Artifact, and specify the source format as `BIOMV100Format` and the type as `FeatureTable[Frequency]`, I get the error "BAD REQUEST - InPath('/home/qiime2/data') is not a file.

In comparison, if I repeat these steps with a folder containing a `BIOMV210Format` file named `feature-table.biom` and don't specify source format, everything works fine.

I see two possible issues here:

1. The code doesn't seem to always detect the `.biom` files, even the `V210` ones, in a directory, if they are not named according to some convention it likes.
2. The code doesn't seem to be able to handle directory input for files which are not `V210`, such as `V100` files.

Are these problems which should be fixed?  If so, should we reopen this issue to address issue 2, and then create a new issue for issue 1, as above?
