### ISSUE TITLE
failure when trying to "Run again"

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/q2studio#82]
I ran a visualizer with `q2-dada2`'s `plot_qualities`. After it completed I hit "Run again" and got the following error:

![screenshot 2016-09-27 14 57 30](https://cloud.githubusercontent.com/assets/192372/18893483/fe646fc6-84c2-11e6-82ad-9eaf2d75e6f1.png)

I'm running this in dev mode.

**Comment by jakereps** [comment]
Thanks @gregcaporaso! Looks like an issue with the new `webview` dynamic resizing. Must not exist for a second in between runs, I'll look into it 👍
